name: Deploy to Aliyun Server

on:
  push:
    branches: [ master, main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --registry https://registry.npmmirror.com/
    
    - name: Build application
      run: CI=false npm run build
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/script-app/script-app
          git pull origin master
          npm ci --registry https://registry.npmmirror.com/
          npm run build
          sudo systemctl reload nginx
          echo "Deployment completed at $(date)"
